// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "Friendly Dino Buddy":return img`
. . . . c c c c c . . . . . . . 
. . c c 5 5 5 5 5 c . . . . . . 
. c 5 5 5 5 1 f 5 5 c . . . . . 
c 5 5 5 5 5 f f 5 5 5 c . . . . 
c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
c c b b 1 b 5 5 5 5 5 5 c . . . 
c 5 3 3 3 5 5 5 5 5 5 5 d c . . 
c 5 5 5 5 5 5 5 5 5 d d d c . . 
. c 5 5 5 5 b 5 5 5 d d d c . . 
. . c b b c 5 5 b d d d d c . . 
. c b b c 5 5 b b d d d d c c . 
. c c c c c b b d d d d d d c c 
. . . c c 5 5 b 5 5 d d d d d c 
. . . . c b 5 5 b b c c c c c c 
. . . . c c c c c c . . . . . . 
. . . . . c b b b c . . . . . . 
`;
            case "image1":
            case "Friendly Death Ghost":return img`
........................
........................
........................
........fffff...........
......ff11111ff.........
.....fb1111111bff.......
.....fd11111111ff.......
...ffdd11111111ddf......
...ffddd1111111ddf......
...ffddddddd111ddf......
...ffbdddddb5d1ddf......
...ffcbbbddc5ddbbf......
.....fcbb111111ff.......
.....fcbb111111ff.......
.....5ffffff1b1ff5......
......fb1111cfbff.......
......ffb11b1ff.........
...ff.fffbbfbf.....55...
...ffffffffff...........
.....ffffff....55.......
........................
........................
.....5..................
........................
`;
            case "image3":
            case "P1":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......fd1111111f.......
......fdd1111111df......
......fddd111111df......
......fdddddd111df......
......fbddddb5d1df......
......fcbbbdc5ddbf...5..
.......fcbb11111f.......
........fffff1b1f.......
........fb111cfbf.......
.5......ffb1b1ff..5.....
......f.fffbfbf.........
......ffffffff...5...5..
.......fffff............
........................
........5...............
................5.......
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
